use("my-ecommerce-project");

// Clear existing data
db.users.deleteMany({});

// Insert mock data for Users collection
db.users.insertMany([
  {
    _id: "00001",
    first_name: "Alie",
    last_name: "Blackcobra",
    username: "alie_blackcobra",
    password: "arbockcalb",
    address: "123/45, Soi 1, Sukhumvit Rd., Bangkok, 10110",
    email: "alie_blackcobra@gmail.com",
    phone: "081-332-4243",
  },
  {
    _id: "00002",
    first_name: "Somchai",
    last_name: "Jaidee",
    username: "somchai_j",
    password: "password2026",
    address: "45/1, Chang Klan Rd., Mueang, Chiang Mai, 50100",
    email: "somchai.jaidee@outlook.com",
    phone: "089-765-4321",
  },
  {
    _id: "00003",
    first_name: "John",
    last_name: "Smith",
    username: "john_smith99",
    password: "securepass123",
    address: "789, Tha Phae Rd., Mueang, Chiang Mai, 50300",
    email: "john.smith@hotmail.com",
    phone: "082-111-2233",
  },
  {
    _id: "00004",
    first_name: "Anong",
    last_name: "Rattana",
    username: "anong_r",
    password: "mysecretpwd",
    address: "12/3, Mittraphap Rd., Mueang, Khon Kaen, 40000",
    email: "anong.rattana@yahoo.com",
    phone: "084-555-6677",
  },
  {
    _id: "00005",
    first_name: "Michael",
    last_name: "Johnson",
    username: "mike_j",
    password: "mikequeen20",
    address: "55, Jomtien Beach Rd., Bang Lamung, Chonburi, 20150",
    email: "michael.j@gmail.com",
    phone: "083-444-5566",
  },
  {
    _id: "00006",
    first_name: "Preecha",
    last_name: "Srisai",
    username: "preecha_sri",
    password: "preechapass",
    address: "99/4, Phetkasem Rd., Hat Yai, Songkhla, 90110",
    email: "preecha.srisai@outlook.co.th",
    phone: "081-999-8888",
  },
  {
    _id: "00007",
    first_name: "Sarah",
    last_name: "Connor",
    username: "s_connor",
    password: "t800savior",
    address: "202, Thalang Rd., Mueang, Phuket, 83000",
    email: "sconnor@icloud.com",
    phone: "086-123-4567",
  },
  {
    _id: "00008",
    first_name: "Kitti",
    last_name: "Sakda",
    username: "kitti_sak",
    password: "kittisecure",
    address: "34, Chonprathan Rd., Hua Hin, Prachuap Khiri Khan, 77110",
    email: "kitti.sakda@gmail.com",
    phone: "085-321-7654",
  },
  {
    _id: "00009",
    first_name: "Yuki",
    last_name: "Tanaka",
    username: "yuki_t",
    password: "tokyotobkk",
    address: "88/8, Ratchadamnoen Rd., Mueang, Nakhon Ratchasima, 30000",
    email: "yuki.tanaka@outlook.com",
    phone: "087-888-9900",
  },
  {
    _id: "00010",
    first_name: "Chayanisa",
    last_name: "Wongsuwan",
    username: "chaya_w",
    password: "chayanisa25",
    address: "15, Rama 9 Rd., Huai Khwang, Bangkok, 10310",
    email: "chayanisa.w@gmail.com",
    phone: "089-456-1234",
  },
  {
    _id: "00011",
    first_name: "David",
    last_name: "Miller",
    username: "david_m",
    password: "millerlight1",
    address: "456, Chao Fa West Rd., Chalong, Phuket, 83130",
    email: "david.miller@live.com",
    phone: "082-777-8899",
  },
  {
    _id: "00012",
    first_name: "Nattaporn",
    last_name: "Thongdee",
    username: "nat_thong",
    password: "natthongpass",
    address: "71/2, Phra Pok Klao Rd., Mueang, Chiang Mai, 50200",
    email: "nattaporn.t@outlook.com",
    phone: "081-443-2211",
  },
  {
    _id: "00013",
    first_name: "Emma",
    last_name: "Watson",
    username: "emma_w",
    password: "hermione123",
    address: "101, Sukhumvit 55 Rd., Watthana, Bangkok, 10110",
    email: "emma.watson@gmail.com",
    phone: "088-999-1122",
  },
  {
    _id: "00014",
    first_name: "Santi",
    last_name: "Meekhun",
    username: "santi_m",
    password: "santipassword",
    address: "5, Nimanhemin Rd. Soi 9, Mueang, Chiang Mai, 50200",
    email: "santi.mee@yahoo.com",
    phone: "085-667-8899",
  },
  {
    _id: "00015",
    first_name: "Robert",
    last_name: "Downey",
    username: "rdj_iron",
    password: "loveyou3000",
    address: "22/11, Pattaya Sai 2 Rd., Bang Lamung, Chonburi, 20150",
    email: "robert.downey@hotmail.com",
    phone: "083-111-4455",
  },
  {
    _id: "00016",
    first_name: "Siriporn",
    last_name: "Phaisarn",
    username: "siriporn_p",
    password: "siri2026pass",
    address: "142, Maliwan Rd., Mueang, Khon Kaen, 40000",
    email: "siriporn.phai@gmail.com",
    phone: "084-222-3344",
  },
  {
    _id: "00017",
    first_name: "Hans",
    last_name: "Muller",
    username: "hans_m",
    password: "berlintobkk",
    address: "9/3, Niphat Uthit 3 Rd., Hat Yai, Songkhla, 90110",
    email: "hans.muller@outlook.com",
    phone: "089-111-5566",
  },
  {
    _id: "00018",
    first_name: "Teerapat",
    last_name: "Boonmee",
    username: "teerapat_b",
    password: "teerapat99",
    address: "305, Charoen Krung Rd., Sathon, Bangkok, 10120",
    email: "teerapat.b@gmail.com",
    phone: "081-888-7766",
  },
  {
    _id: "00019",
    first_name: "Kim",
    last_name: "Minjun",
    username: "kim_minjun",
    password: "seoulbkkpass",
    address: "67, Uritsadorn Rd., Mueang, Ubon Ratchathani, 34000",
    email: "kim.minjun@gmail.com",
    phone: "086-555-4433",
  },
  {
    _id: "00020",
    first_name: "Pornthip",
    last_name: "Suwan",
    username: "pornthip_s",
    password: "pornthippwd",
    address: "112/5, Phra Baramee Rd., Patong, Kathu, Phuket, 83150",
    email: "pornthip.suwan@outlook.co.th",
    phone: "087-222-8899",
  },
]);

// Find all users
db.users.find({});
